//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mashi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Stores = new HashSet<Store>();
        }
    
        public long CityId { get; set; }
        public string CityName { get; set; }
        public string AbCityName { get; set; }
        public Nullable<short> CountryId { get; set; }
        public Nullable<short> StateId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<Store> Stores { get; set; }
    }
}
