//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mashi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Cities = new HashSet<City>();
            this.States = new HashSet<State>();
            this.Stores = new HashSet<Store>();
        }
    
        public short CountryId { get; set; }
        public string CountryName { get; set; }
        public string CountryCode { get; set; }
        public string AbCountryName { get; set; }
        public string AbCountryCode { get; set; }
        public string CountryMobileCode { get; set; }
    
        public virtual ICollection<City> Cities { get; set; }
        public virtual ICollection<State> States { get; set; }
        public virtual ICollection<Store> Stores { get; set; }
    }
}
