//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mashi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MASHIEntities : DbContext
    {
        public MASHIEntities()
            : base("name=MASHIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<City> Cities { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<EmailAccount> EmailAccounts { get; set; }
        public DbSet<FCMNotification> FCMNotifications { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<NotificationCategory> NotificationCategories { get; set; }
        public DbSet<Permission> Permissions { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<SchemeDocument> SchemeDocuments { get; set; }
        public DbSet<SchemeType> SchemeTypes { get; set; }
        public DbSet<Store> Stores { get; set; }
        public DbSet<StoreCategory> StoreCategories { get; set; }
        public DbSet<Module> Modules { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<RoleModulePermission> RoleModulePermissions { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
    }
}
