//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mashi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public long MessageId { get; set; }
        public string MessageType { get; set; }
        public Nullable<int> EmailAccountId { get; set; }
        public Nullable<int> MailPriority { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string Body { get; set; }
        public string CC { get; set; }
        public string BCC { get; set; }
        public string Subject { get; set; }
        public Nullable<bool> IsAttachment { get; set; }
        public string AttachmentPath { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string SentStatus { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public string DeliverStatus { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string SentResponse { get; set; }
        public string TransactionId { get; set; }
    }
}
