//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mashi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.RoleModulePermissions = new HashSet<RoleModulePermission>();
        }
    
        public int ModuleId { get; set; }
        public string ModuleName { get; set; }
        public string Description { get; set; }
        public string AbModuleName { get; set; }
        public string AbDescription { get; set; }
        public string ApplicationId { get; set; }
        public string Url { get; set; }
        public Nullable<int> ParentModuleId { get; set; }
        public bool IsEnabled { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int ModuleOrder { get; set; }
    
        public virtual ICollection<RoleModulePermission> RoleModulePermissions { get; set; }
    }
}
