//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mashi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationCategory
    {
        public NotificationCategory()
        {
            this.FCMNotifications = new HashSet<FCMNotification>();
        }
    
        public int NotificationCategoryId { get; set; }
        public string NotificationCategoryName { get; set; }
        public string AbNotificationCategoryName { get; set; }
        public bool IsEnable { get; set; }
        public bool IsDeleted { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<FCMNotification> FCMNotifications { get; set; }
    }
}
