//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mashi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public Permission()
        {
            this.RoleModulePermissions = new HashSet<RoleModulePermission>();
        }
    
        public byte PermissionId { get; set; }
        public string PermissionName { get; set; }
        public string Description { get; set; }
        public string AbPermissionName { get; set; }
        public string AbDescription { get; set; }
    
        public virtual ICollection<RoleModulePermission> RoleModulePermissions { get; set; }
    }
}
