//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mashi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleModulePermission
    {
        public int RoleId { get; set; }
        public int ModuleId { get; set; }
        public byte PermissionId { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Permission Permission { get; set; }
        public virtual Module Module { get; set; }
        public virtual Role Role { get; set; }
    }
}
