//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mashi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.RoleModulePermissions = new HashSet<RoleModulePermission>();
        }
    
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public string AbRoleName { get; set; }
        public string Description { get; set; }
        public string AbDescription { get; set; }
        public bool IsEnabled { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
        public string DefaultUrl { get; set; }
    
        public virtual ICollection<RoleModulePermission> RoleModulePermissions { get; set; }
    }
}
