//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mashi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchemeDocument
    {
        public long SchemeDocumentId { get; set; }
        public string SchemeDocumentName { get; set; }
        public string AbSchemeDocumentName { get; set; }
        public string Description { get; set; }
        public string AbDescription { get; set; }
        public string ImagePath { get; set; }
        public string PDFPath { get; set; }
        public int SchemeTypeId { get; set; }
        public Nullable<int> SchemeDocumentOrder { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual SchemeType SchemeType { get; set; }
    }
}
