//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mashi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public long StoreId { get; set; }
        public string StoreCode { get; set; }
        public string StoreName { get; set; }
        public string AbStoreName { get; set; }
        public string StoreOwnerName { get; set; }
        public string AbStoreOwnerName { get; set; }
        public string Description { get; set; }
        public string AbDescription { get; set; }
        public int StoreCategoryId { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<short> CountryId { get; set; }
        public Nullable<short> StateId { get; set; }
        public Nullable<long> CityId { get; set; }
        public string Pincode { get; set; }
        public string AbPincode { get; set; }
        public bool IsEnabled { get; set; }
        public Nullable<int> StoreOrder { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string StoreFor { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
        public virtual StoreCategory StoreCategory { get; set; }
    }
}
