//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mashi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public long UserId { get; set; }
        public string UserName { get; set; }
        public bool IsTrackingEnabled { get; set; }
        public Nullable<short> TrackingInterval { get; set; }
        public Nullable<long> ParentUserId { get; set; }
        public bool IsEnabled { get; set; }
        public string ProfilePhotoPath { get; set; }
        public string Salt { get; set; }
        public byte[] Password { get; set; }
        public string AppMode { get; set; }
        public string FullName { get; set; }
        public string AbFullName { get; set; }
        public string Gender { get; set; }
        public Nullable<short> CountryId { get; set; }
        public Nullable<short> StateId { get; set; }
        public Nullable<long> CityId { get; set; }
        public string EmailId { get; set; }
        public string MobileNumber { get; set; }
        public string UserType { get; set; }
        public string OTP { get; set; }
        public Nullable<bool> IsOTPEnabled { get; set; }
        public Nullable<bool> IsResetDone { get; set; }
        public bool IsPushLogoutEnabled { get; set; }
        public int SOSLimit { get; set; }
        public bool IsTrackEventEnabled { get; set; }
        public string Token { get; set; }
        public bool IsLogin { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<System.DateTime> TokenExpiresOn { get; set; }
        public string ApplicationId { get; set; }
        public string GCMRegistrationId { get; set; }
        public string UniqueCode { get; set; }
        public Nullable<short> UserRating { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
